// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousCommand::AutonomousCommand(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	SetTimeout(5);
	Robot::drive->ResetGyro();
	Robot::drive->SetExp();
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	SmartDashboard::PutNumber("Gyro Angle",Robot::drive->getGAngle());
	static const float kP = .01;
	//Robot::drive->driveMethod(-.3,-.3);

	Robot::drive->RobotDriveDrive(.25, -(Robot::drive->getGAngle() * kP));
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {

	//if (IsTimedOut()) {
		//return true;
	//}
    return false;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	Robot::drive->driveMethod(0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
